name: Deploy to GCP VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on VM
        run: |
          ssh -t -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /home/moshdev2213/test-sp-be
            git reset --hard HEAD
            git clean -fd
            git pull origin master
            sudo systemctl daemon-reload
            sudo systemctl restart test-sp-app.service
            sudo systemctl status test-sp-app.service --no-pager
            journalctl -u test-sp-app.service -n 10 --no-pager
            echo "🚀 test-sp-app service restarted successfully!"
          EOF